# Generated by Django 5.1 on 2024-09-05 14:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('ongoing', 'Ongoing'), ('victory', 'Victory'), ('defeat', 'Defeat')], default='ongoing', max_length=20)),
                ('result', models.CharField(choices=[('ongoing', 'Ongoing'), ('good_ending', 'Good Ending'), ('perfect_ending', 'Perfect Ending'), ('bad_ending', 'Bad Ending')], default='ongoing', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('speaker', models.CharField(choices=[('player', 'Player'), ('demon_lord', 'Demon Lord')], max_length=10)),
                ('content', models.TextField()),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='game.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_persuasion_level', models.IntegerField(default=0)),
                ('demon_lord_resistance', models.IntegerField(default=100)),
                ('player_emotional_state', models.CharField(default='neutral', max_length=50)),
                ('demon_lord_emotional_state', models.CharField(default='hostile', max_length=50)),
                ('argument_strength', models.IntegerField(default=0)),
                ('environmental_factors', models.JSONField(default=dict)),
                ('game_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gamesession',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player'),
        ),
        migrations.CreateModel(
            name='StoryProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_chapter', models.IntegerField(default=1)),
                ('progress', models.IntegerField(default=0)),
                ('game_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.gamesession')),
            ],
        ),
    ]
