# Generated by Django 5.1 on 2024-08-25 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemonLord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('health', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('accuracy', models.FloatField()),
                ('evasion', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('health', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('accuracy', models.FloatField()),
                ('evasion', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecialAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cooldown', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_turn', models.IntegerField(default=1)),
                ('is_completed', models.BooleanField(default=False)),
                ('winner', models.CharField(blank=True, choices=[('HERO', 'Hero'), ('DEMON', 'Demon Lord')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demon_lord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.demonlord')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.hero')),
            ],
        ),
        migrations.CreateModel(
            name='GameAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.IntegerField()),
                ('actor', models.CharField(choices=[('HERO', 'Hero'), ('DEMON', 'Demon Lord')], max_length=10)),
                ('action_type', models.CharField(choices=[('ATTACK', 'Attack'), ('DEFEND', 'Defend'), ('SPECIAL', 'Special Move')], max_length=10)),
                ('action_result', models.CharField(choices=[('HIT', 'Hit'), ('MISS', 'Miss'), ('EVADE', 'Evaded'), ('CRITICAL', 'Critical Hit')], max_length=10)),
                ('damage_dealt', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='game.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='HeroAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_used', models.IntegerField(default=0)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='game.hero')),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.specialability')),
            ],
        ),
        migrations.CreateModel(
            name='DemonLordAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_used', models.IntegerField(default=0)),
                ('demon_lord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='game.demonlord')),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.specialability')),
            ],
        ),
    ]
