# Generated by Django 5.1 on 2024-09-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyprogress',
            name='plot_points',
            field=models.JSONField(default=list),
        ),
    ]
