# Generated by Django 5.1 on 2024-08-25 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroability',
            name='ability',
        ),
        migrations.RemoveField(
            model_name='heroability',
            name='hero',
        ),
        migrations.AddField(
            model_name='demonlord',
            name='curse_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='demonlord',
            name='is_cursed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demonlord',
            name='mana',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='demonlord',
            name='max_health',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='demonlord',
            name='max_mana',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='hero',
            name='curse_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='is_cursed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hero',
            name='mana',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='hero',
            name='max_health',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='hero',
            name='max_mana',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='hero',
            name='player',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialability',
            name='mana_cost',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='demonlord',
            name='accuracy',
            field=models.FloatField(default=0.8),
        ),
        migrations.AlterField(
            model_name='demonlord',
            name='attack',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='demonlord',
            name='defense',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='demonlord',
            name='evasion',
            field=models.FloatField(default=0.2),
        ),
        migrations.AlterField(
            model_name='demonlord',
            name='health',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='gameaction',
            name='action_type',
            field=models.CharField(choices=[('ATTACK', 'Attack'), ('DEFEND', 'Defend'), ('SPECIAL', 'Special Move'), ('CURSE', 'Curse')], max_length=10),
        ),
        migrations.AlterField(
            model_name='hero',
            name='accuracy',
            field=models.FloatField(default=0.8),
        ),
        migrations.AlterField(
            model_name='hero',
            name='attack',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='hero',
            name='defense',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='hero',
            name='evasion',
            field=models.FloatField(default=0.2),
        ),
        migrations.AlterField(
            model_name='hero',
            name='health',
            field=models.IntegerField(default=100),
        ),
        migrations.CreateModel(
            name='CharacterAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_used_turn', models.IntegerField(default=0)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.specialability')),
                ('demon_lord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='game.demonlord')),
                ('hero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='game.hero')),
            ],
        ),
        migrations.DeleteModel(
            name='DemonLordAbility',
        ),
        migrations.DeleteModel(
            name='HeroAbility',
        ),
    ]
