# Generated by Django 5.1 on 2024-08-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_heroability_ability_remove_heroability_hero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='max_turns',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='current_turn',
            field=models.IntegerField(default=0),
        ),
    ]
