# Generated by Django 5.1 on 2024-09-07 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_storyprogress_plot_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=50)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('final_persuasion_level', models.FloatField()),
                ('final_demon_resistance', models.FloatField()),
                ('final_chapter', models.IntegerField()),
                ('total_turns', models.IntegerField()),
                ('duration', models.DurationField()),
                ('game_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_result', to='game.gamesession')),
            ],
        ),
    ]
