# Generated by Django 5.1 on 2024-08-31 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gamesession_max_turns_alter_gamesession_current_turn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterability',
            name='ability',
        ),
        migrations.RemoveField(
            model_name='characterability',
            name='demon_lord',
        ),
        migrations.RemoveField(
            model_name='characterability',
            name='hero',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='demon_lord',
        ),
        migrations.RemoveField(
            model_name='gameaction',
            name='game_session',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='player',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='hero',
        ),
        migrations.RenameField(
            model_name='gamesession',
            old_name='created_at',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='current_turn',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='max_turns',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='winner',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='outcome',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('victory', 'Victory'), ('defeat', 'Defeat')], default='ongoing', max_length=20),
        ),
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('speaker', models.CharField(choices=[('player', 'Player'), ('demon_lord', 'Demon Lord')], max_length=10)),
                ('content', models.TextField()),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='game.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_persuasion_level', models.IntegerField(default=0)),
                ('demon_lord_resistance', models.IntegerField(default=100)),
                ('player_emotional_state', models.CharField(default='neutral', max_length=50)),
                ('demon_lord_emotional_state', models.CharField(default='hostile', max_length=50)),
                ('argument_strength', models.IntegerField(default=0)),
                ('environmental_factors', models.JSONField(default=dict)),
                ('game_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player'),
        ),
        migrations.CreateModel(
            name='StoryProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_chapter', models.IntegerField(default=1)),
                ('plot_points', models.JSONField(default=dict)),
                ('game_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.gamesession')),
            ],
        ),
        migrations.DeleteModel(
            name='SpecialAbility',
        ),
        migrations.DeleteModel(
            name='CharacterAbility',
        ),
        migrations.DeleteModel(
            name='DemonLord',
        ),
        migrations.DeleteModel(
            name='GameAction',
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
