# Generated by Django 5.1 on 2024-09-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_gamesession_is_completed_gamesession_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storyprogress',
            name='next_chapter_threshold',
        ),
        migrations.RemoveField(
            model_name='storyprogress',
            name='plot_points',
        ),
        migrations.RemoveField(
            model_name='storyprogress',
            name='story_path',
        ),
        migrations.AddField(
            model_name='storyprogress',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
