# Generated by Django 5.1 on 2024-09-05 08:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_storyprogress_next_chapter_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
