# Generated by Django 5.1 on 2024-09-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_gamesession_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='outcome',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('victory', 'Victory'), ('defeat', 'Defeat')], default='ongoing', max_length=20, null=True),
        ),
    ]
