# Generated by Django 5.1 on 2024-09-05 08:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_gamesession_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
