# Generated by Django 5.1 on 2024-09-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_gamesession_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='is_completed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
