# Generated by Django 5.1 on 2024-09-05 09:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_gamesession_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='outcome',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('victory', 'Victory'), ('defeat', 'Defeat')], default='ongoing', max_length=20),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='result',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('good_ending', 'Good Ending'), ('perfect_ending', 'Perfect Ending'), ('bad_ending', 'Bad Ending')], default='ongoing', max_length=20),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
